### ISSUE TITLE
If you use Frobenius norm, I think you forgot to take a square root of sum of all squared elements of matrix.

### ISSUE THREAD

**Issue by Biunovich** [mrcdr/lambda-lanczos#1]
I think here should be `return std::sqrt(r2);`

https://github.com/mrcdr/lambda-lanczos/blob/0858d408757c0f601130ad5a0e37306261eb148a/include/lambda_lanczos/lambda_lanczos.hpp#L310

**Comment by mrcdr** [comment]
Thank you for your comment and your indication is right.
The routine may cause trouble in the situation `r2` < 1. I've forgotten that!
I'll fix it to use sqrt or 1-norm.
Thank you again.

**Comment by mrcdr** [comment]
The issue fixed at aa3d260.
