### ISSUE TITLE
Position of the largest Eigenvector

### ISSUE THREAD

**Issue by dominik-kopczynski** [mrcdr/lambda-lanczos#11]
Hi mrcdr,

I very much like your implementation :-) Is there any possibility to figure out the original column / position of the largest Eigenvector? This information could be necessary to me.

Cheers,
Dominik

**Comment by mrcdr** [comment]
Thank you for your comment.

The `run()` returns only one eigenvector that corresponds to either the largest eigenvalue or the smallest eigenvalue depending on the third argument `find_maximum`. So the position of the returned eigenvector should be
- (_n_-1)th, if the third argument is `true`
- 0th, if the third argument is `false`

for an _n_ by _n_ matrix if one could know all _n_ eigenvectors in ascending eigenvalue order.

(I may have misunderstood your question. I welcome your other comments.)

Regards,
mrcdr

**Comment by dominik-kopczynski** [comment]
Hi mcrdr,

Thank you for your answer. My bad, I guess, that I might misunderstand the concept of eigenvalues and how you are computing them. Thank you once again :-)

Cheers

**Comment by mrcdr** [comment]
Hello Dominik,

Thank you too for being interested in my library!

Best,
mrcdr
