### ISSUE TITLE
Possible parallelization

### ISSUE THREAD

**Issue by Mbakhov** [mrcdr/lambda-lanczos#12]
Hi! Thank you for the provided package. 

Currently, I need to calculate the smallest algebraic eigenvalue of large matrices (>1mln x 1mln). The current serial version is definitely not adapted for this purpose. What do you think, is it possible to parallelize the code using OpenMp (possibly some loops)?
Thank you!
Murod

**Comment by mrcdr** [comment]
Thank you for your comment!

I think most part of Lanczos calculation time is consumed by the matrix-vector multiplication routine `mv_mul` normally. So I believe it is effective enough to parallelize the routine (which can be done without any modification of the library).

But if more speed is needed,  providing an option to link a parallelized linear algebra library (such as OpenBLAS) would be easy and reasonable.

Best,
mrcdr

**Comment by Beck-919** [comment]
I was waiting for @mrcdr to comment before replying on the same. 

@Mbakhov, if you are looking for  GPU parallelism you can check out my repo [acc-lanczos](https://github.com/Beck-919/acc-lanczos), which is derived from this repo (@mrcdr, please feel free to review it!).

There I have provided a template to adapt workloads for GPU parallelism.
