### ISSUE TITLE
references to std::cout in lambda_lanczos.hpp

### ISSUE THREAD

**Issue by jewettaij** [mrcdr/lambda-lanczos#3]
I just wanted to point out that lambda_lanczos.hpp uses std::cout.  I suggest adding 
```
#include <iostream>
```
to the beginning of the file.
Cheers

Andrew

**Comment by jewettaij** [comment]
Sorry for the typo.  I meant to say
```
#include <iostream>
```
not

*include*

**Comment by mrcdr** [comment]
Thank you for your comment!

I removed all use of `cout` and `endl` then deleted `#include <iostream>` after debugging.
But I've forgotten to remove `using` declarations!
I should remove them too and I'll do it soon.

Thank you again,

**Comment by jewettaij** [comment]
Great.  I'll close this issue.
