### ISSUE TITLE
simply #include path in lambda_lanczos.hpp

### ISSUE THREAD

**Issue by jewettaij** [mrcdr/lambda-lanczos#4]
A small suggestion:
Replace:
```
#include <lambda_lanczos/lambda_lanczos_util.hpp>
```
with
```
#include <lambda_lanczos_util.hpp>
```
(You will also have to modify the files in the [src](https://github.com/mrcdr/lambda-lanczos/tree/master/src) directory and change the g++ arguments.)

It is not necessary to move **lambda_lanczos.hpp** or **lambda_lanczos_util.hpp**.  They can remain inside the **lambda_lanczos/** subdirectory.  But changing the **#include** statement in **lambda_lanczos.hpp** will give other developers more freedom to move your files where they prefer.

For example, I use your lambda_lanczos repository as a [git submodule](https://github.blog/2016-02-01-working-with-submodules) inside [one of my repositories](https://github.com/jewettaij/superpose3d_cpp).  *(Including your code as a submodule prevents me from modifying your code.)*

People who use my repository will probably copy your files to a new directory containing my code.  They must move your files to a "lambda_lanczos/" subdirectory, or modify the #include statements.  I think C++ programmers are smart enough to figure this out.  Anyway, I added a [warning message](https://github.com/jewettaij/superpose3d_cpp#additional-modifications-needed).

This is a very small issue.  I hesitate to bother you.  (Perhaps I should avoid using git submodules.)

**Comment by mrcdr** [comment]
Thank you for your comment.

That's good idea! I worried about many header files inside single directory cause inconvenience,
but there is no problem to decrease include-path depth as you mentioned.
I'll fix it soon.

Thank you so much!

**Comment by mrcdr** [comment]
fixed at b10c323cdd642e269a318666be37c834bab4318d

**Comment by jewettaij** [comment]
Thanks.
I updated my repository accordingly and everything is working now.
Cheers

**Comment by jewettaij** [comment]
Hi Yuya
   I just wanted to let you know that:

1) Your code was accepted into LAMMPS
2) Unfortunately, the commit history of the file containing your code was erased so you did not get credit for your contribution on github.  (It looks like this happened when Jacob Gissinger sent the final pull request to the LAMMPS developers.)

So [I have requested](https://github.com/lammps/lammps/issues/2321) that the LAMMPS developers approve a pull request from you so that your name will be included in the list of LAMMPS developers:

***EDIT: Please postpone this suggestion for now:***

~~To solve this:~~

~~1) update your fork to the latest version of LAMMPS~~

~~2) Optional: move the "math_eigen.h" file to "src/"~~

~~git mv src/USER_REACTION/math_eigen.h src/~~

~~(By the time you read this, the file may already have been moved there.  In that case, make some small trivial change to the file, such as adding a blank line to this file.)~~

~~3) Submit a pull request~~

I will let you know when I hear back from the LAMMPS developers.  I'm sorry to create more trouble for you.

Hello, by the way.

Andrew

**Comment by jewettaij** [comment]
~~...I forgot to mention this:  When you submit the pull request on the github we page, you will have an opportunity to explain the  reason for modifying the code.  Here you can say that you are the principle author of the "math_eigen.h" file (to make sure they know who you are).  Perhaps I did not need to suggest this. (I worry that if your pull request is blank, and there is no description explaining why you made this pull request, they might reject it.)~~

~~Please let me know if your pull request is rejected.~~

**Comment by jewettaij** [comment]
Dear Yuya
   Please ignore my previous messages.  I received a reply from the LAMMPS developers.  They want me to make some changes to "math_eigen.h".  I will do this first.  Then I will contact you when it is a good time for you to submit your pull request.
   Thank you.
Andrew
